### ISSUE TITLE
About the mesh in this project

### ISSUE THREAD

**Issue by canhongluori** [nmartin198/MOD_FreeSurf2D#1]
Hello sir, Does this model use structured mesh or unstructured mesh?

**Comment by nmartin198** [comment]
A structured mesh is used. It is a regular mesh in that different DX an DY dimensions can be used but there is one DX and one DY for the entire domain.

**Comment by canhongluori** [comment]
Hello sir， I have read the paper about the MOD_FreeSurf2D，this model use quad and structured mesh，what should I do If I want to add function about use triangle mesh and unstructured mesh?

**Comment by nmartin198** [comment]
Hello canhongluori,

The MOD_FreeSurf2D uses the TRIM algorithms developed by Dr. Casulli. There
are several related papers and works that provide methods of using
unstructured meshes with these algorithms. I have listed a couple of papers
below. It should be feasible to convert the code to use unstructured meshes
and I think it would be great if you wanted to try it.

   - Casulli, V., 1997. Numerical simulation of three-dimensional free
   surface flow in isopycnal coordinates. International Journal for Numerical
   Methods in Fluids 25, 645–658.
   - Walters, R.A., Casulli, V., 1998. A robust, finite element model for
   hydrostratic surface water flows. Communications in Numerical Methods in
   Engineering 14, 931–940.

Also there is a more advanced 3D code for coastal dynamics that was
originally built on the same TRIM algorithms that uses unstructured meshes.
This code is called SUNTANS and you can access the source code at:

https://github.com/ofringer/suntans

I hope this might be helpful. And, I wish you all the best in whatever
approaches that you might want to try.

Best Regards,

Nick

**Comment by canhongluori** [comment]
OK， thank you Professioner
